spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

product-nutrition:
  base-path: http://localhost:8081

logging:
  level:
    org.springframework.security: INFO

springdoc:
  api-docs:
    path: /custom-api-docs
  swagger-ui:
    path: /custom-swagger-ui

jwt:
  signing-secret-key: ${JWT_SIGNING_SECRET_KEY}

