openapi: 3.0.0
info:
  title: Products API
  description: API for managing products
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Local development server

paths:
  /v2/product-nutrition/{product-id}:
    get:
      tags:
        - ProductNutrition
      operationId: getProductNutritionByIdV2
      parameters:
        - name: product-id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The requested product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductNutritionV2'

components:
  schemas:
    ProductNutritionV2:
      type: object
      required:
        - productId
        - title
        - proteins
        - fats
        - carbohydrates
        - calories
        - nutritionType
      properties:
        productId:
          type: string
          example: 1
          description: Unique identifier of the product
        title:
          type: string
          example: Chicken breast
          description: Name of the product
        proteins:
          type: integer
          format: int32
          example: 20
          description: Amount of proteins in grams per serving
        fats:
          type: integer
          format: int32
          example: 5
          description: Amount of fats in grams per serving
        carbohydrates:
          type: integer
          format: int32
          example: 0
          description: Amount of carbohydrates in grams per serving
        calories:
          type: integer
          format: int32
          example: 100
          description: Total calories per serving
        nutritionType:
          type: string
          description: Type of nutrition
          example: VEGAN
          enum:
            - VEGAN
            - NON_VEGETARIAN
          x-enum-varnames:
            - VEGAN
            - NON_VEGETARIAN
