openapi: 3.0.0
info:
  title: Products API
  description: API for managing products
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Local development server

paths:
  /product-nutrition/{product-id}:
    get:
      tags:
        - ProductNutrition
      operationId: getProductById
      parameters:
        - name: product-id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductNutrition'

components:
  schemas:
    ProductNutrition:
      type: object
      required:
        - productId
        - title
        - proteins
        - fats
        - carbohydrates
        - calories
      properties:
        productId:
          type: string
          description: Unique identifier of the product
        title:
          type: string
          description: Name of the product
        proteins:
          type: integer
          format: int32
          description: Amount of proteins in grams per serving
        fats:
          type: integer
          format: int32
          description: Amount of fats in grams per serving
        carbohydrates:
          type: integer
          format: int32
          description: Amount of carbohydrates in grams per serving
        calories:
          type: integer
          format: int32
          description: Total calories per serving
